[package]
name = "oilarra"
version = "0.1.0"
authors = ["Frederik Deweerdt <frederik.deweerdt@gmail.com>"]

[dependencies.nickel]
version = "*"
#features = ["unstable"]

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
